### ISSUE TITLE
Easiest way to remove a table?

### ISSUE THREAD

**Issue by isaachinman** [jonseg/crud-admin-generator#109]
Thanks for this project, it's helped us get an admin backoffice up and running very quickly.

Quick question: what's the easiest way to remove a table from the application? There are some tables in our database which we do not want to allow reading or writing of, and thus need to be removed from the automatically-generated content provided by this application.

If I simply remove lines from `web/controllers/base.php`, I get a bunch of errors.

**Comment by isaachinman** [comment]
@jonseg ?

**Comment by jonseg** [comment]
You need remove the line in /web/controllers/base.php that includes (require_once) the file relationed with the table. Also, you need find the menu option that load your table in /web/views/menu.html.twig and remove too.

Regards.

**Comment by isaachinman** [comment]
Got it, thanks. It was the `menu.html.twig` bit that wasn't so clear. Cheers again for a great project.
