### ISSUE TITLE
Installation error on mac, xampp

### ISSUE THREAD

**Issue by aldeacms** [jonseg/crud-admin-generator#29]
I'm following your installation steps, but when I write "php composer.phar install" I'm getting this error : 
![screen shot 2014-11-03 at 11 40 13 pm](https://cloud.githubusercontent.com/assets/1361751/4894061/08df2500-63cc-11e4-8ad6-24d0bfcb22eb.png)

What's wrong? What can I do?

Thank you :)

**Comment by tanujs22** [comment]
Awesome
