### ISSUE TITLE
generate:admin not generating views

### ISSUE THREAD

**Issue by port22** [jonseg/crud-admin-generator#31]
I'm following the installation instructions exactly, but at the point where I run

php console generate:admin

It will not generate the views for my database tables. The command does not output any error and the database connection is OK. The website is generated successfully (actually it is working before the generate command).

Am I missing something to do which is not in the installation instruction or is a php requirement missing ?

here my commands I'm excuting:

git clone https://github.com/jonseg/crud-admin-generator.git admingenerator
cd admingenerator
curl -sS https://getcomposer.org/installer | php
php composer.phar install
edit src/app.php and fill in db-data, leaving /resources as it is
create nginx virtualhost pointing root to admingenerator/web/ -> admin website is working at this point correctly
php console generate:admin -> nothing happens, not even with -vvv (verbose) any output -> still no views for my tables

**Comment by jonseg** [comment]
Hi,

Do your tables have primary keys? Can you paste the structure of your tables?

Thank you.

**Comment by port22** [comment]
embarrassing, yes - for the quick test I did not set a primary key. Now it works. Maybe add this hint to the installation instructions for other people as dumb as me :-P
thanks for the tip!

**Comment by mlungsta** [comment]
Hello i have encounted a problem and i am not sure how to solve it;
Fatal error: class 'symfony\component\console\application' not found in ...\src\console.php on line 20

Could you please assit.
