### ISSUE TITLE
Lot of "deprecated" alerts on edit and update

### ISSUE THREAD

**Issue by manuelbcd** [jonseg/crud-admin-generator#34]
Hello, I'm facing some problems creating crud forms.  I can navigate through views but if y edit or update any row, get lot of messages like these:

Deprecated: ValidatorInterface was deprecated in version 2.5 and will be removed in version 3.0. Please use Validator\ValidatorInterface instead. in C:\MYPATH\htdocs\admin-generator\vendor\symfony\validator\Symfony\Component\Validator\ValidatorInterface.php on line 14

Deprecated: The "Symfony\Component\Validator\MetadataFactoryInterface" interface is deprecated since version 2.5 and will be removed in Symfony 3.0. You should use the "Symfony\Component\Validator\Mapping\Factory\MetadataFactoryInterface" interface instead. in C:\MYPATH\htdocs\admin-generator\vendor\symfony\validator\Symfony\Component\Validator\MetadataFactoryInterface.php on line 14

Deprecated: The "Symfony\Component\Validator\Mapping\ElementMetadata" class was deprecated in version 2.5 and will be removed in 3.0. Use "Symfony\Component\Validator\Mapping\GenericMetadata" instead. in C:\MYPATH\htdocs\admin-generator\vendor\symfony\validator\Symfony\Component\Validator\Mapping\ElementMetadata.php on line 14

Deprecated: Symfony\Component\Validator\MetadataInterface was deprecated in version 2.5 and will be removed in 3.0. Use Symfony\Component\Validator\Mapping\MetadataInterface instead. in C:\MYPATH\htdocs\admin-generator\vendor\symfony\validator\Symfony\Component\Validator\MetadataInterface.php on line 14

... ( and more ) ...

**Comment by jonseg** [comment]
I have updated composer.json file.
You need delete the vendor folder and execute this command again:
```
php composer.phar install
```
