### ISSUE TITLE
Running php console generate:admin after changing DB does not add new tables

### ISSUE THREAD

**Issue by eschopler1** [jonseg/crud-admin-generator#40]
Hello,

When I rerun the php console generate:admin command, I do not see the new tables for views and controllers I created. I have tried cloning the crud generator again but no help.

**Comment by eschopler1** [comment]
To clarify, I have run php console generate:admin command, added a simple table with a foreign key relation, and then reran the php console generate command again. The table does not show up.

**Comment by eschopler1** [comment]
Nevermind, found the issue, I have to have a primary key for the table or it will not generate!

**Comment by blag001** [comment]
If you've found the bug, don't forget to close this thread ;)

**Comment by netblade123** [comment]
I have the same problem, can someone please help me.

**Comment by blag001** [comment]
if you re-build from a clean version, what de you get ? 
- nothing => not good... show you .sql gen file for your DB
- only old table => take a look at you primary-key / auto-increment 
- everything => you're welcome :P

**Comment by netblade123** [comment]
I have clean version only.
But I can't see any .sql file, also all tables have primary-key / auto-increment.

**Comment by blag001** [comment]
for the .sql, I mean an export of your database (aka the sql source code to make the DB)
If you can show us, it'll help I think.

When you run the generate:admin, de you got any table found ?
(check if you have table-labeled folder in `crud-generator/web/controllers/`)

**Comment by netblade123** [comment]
Yes, table was generated in controller and views folder.

Thanks.

-- 
Best Regards,

Sintu Gupta
Web Development Team Leader
netBlade Solutions Pvt. Ltd.
+91 251 648 2448
www.netblade.co.in

**Comment by blag001** [comment]
So everything work ?

**Comment by netblade123** [comment]
No.

Thanks.

-- 
Best Regards,

Sintu Gupta
Web Development Team Leader
netBlade Solutions Pvt. Ltd.
+91 251 648 2448
www.netblade.co.in

**Comment by blag001** [comment]
open your own issues please, with every data you can put inside,
like screen shot, what you have configure and everything

**Comment by netblade123** [comment]
I used the steps from *http://crud-admin-generator.com/
<http://crud-admin-generator.com/>*

Thanks.

-- 
Best Regards,

Sintu Gupta
Web Development Team Leader
netBlade Solutions Pvt. Ltd.
+91 251 648 2448
www.netblade.co.in
