### ISSUE TITLE
[BUG] Table with primary key on multiple columns don't show

### ISSUE THREAD

**Issue by blag001** [jonseg/crud-admin-generator#43]
If you have something like this : 
```SQL
CREATE TABLE IF NOT EXISTS `localiserservice` (
  `service_id` int(10) unsigned NOT NULL,
  `site_id` int(10) unsigned NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `localiserservice` ADD PRIMARY KEY (`service_id`,`site_id`);

CREATE TABLE IF NOT EXISTS `service` (
  `id_service` int(10) unsigned NOT NULL,
  `srv_libelle` varchar(100) NOT NULL,
  `srv_description` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `service` ADD PRIMARY KEY (`id_service`);

CREATE TABLE IF NOT EXISTS `site` (
  `id_site` int(10) unsigned NOT NULL,
  `sit_libelle` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `site` ADD PRIMARY KEY (`id_site`);
```
(sorry for the French)
`console generate:admin` only generate 2 of the 3 tables, `localiserservice` is missing... :-/

**Comment by blag001** [comment]
`localiserservice` don't have `auto_increment` column, but I have on the 2 other : 
```SQL
ALTER TABLE `service` MODIFY `id_service` int(10) unsigned NOT NULL AUTO_INCREMENT;

ALTER TABLE `site` MODIFY `id_site` int(10) unsigned NOT NULL AUTO_INCREMENT;
```

**Comment by zhujiaqi** [comment]
from console.php theres

if($primary_keys === 1 || ($primary_keys > 1 && $primary_keys_auto === 1)){...}
else {continue;}

in your case `localiserservice` has two primary keys:

mysql> show columns from localiserservice;
+------------+------------------+------+-----+---------+-------+
| Field      | Type             | Null | Key | Default | Extra |
+------------+------------------+------+-----+---------+-------+
| service_id | int(10) unsigned | NO   | PRI | NULL    |       |
| site_id    | int(10) unsigned | NO   | PRI | NULL    |       |
+------------+------------------+------+-----+---------+-------+
2 rows in set (0.01 sec)

and that statement is FALSE, thus continue.

I don't know why it worked this way but it seems either make it single primary key plus an unique index of the two columns could fix this.

p.s: I think this project is obsoleted.

**Comment by jonseg** [comment]
Hi,

In this version of "crud admin generator", the tables must have one primary key or multiple primary keys with one of them as autoincrement.

I will improve in the next version, or you can send a pull request :)

Thank you.

**Comment by blag001** [comment]
@zhujiaqi yes, I saw the same code when I was looking for this bug; but I can't change my DB...
"I think this project is obsoleted" => I don't find another good one; but yes, some part of this project need update.

@jonseg I'll send you a pull request I think (I've another one to send too).

**Comment by blag001** [comment]
@jonseg question: 
Not allowing multiple primary keys without autoincrement had some reason ? 
or it was just to keep it simple ?
