### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by pratamawijaya** [jonseg/crud-admin-generator#45]
NotFoundHttpException in RouterListener.php line 144:
No route found for "GET /category/web/resources/css/bootstrap.min.css" (from "http://128.199.xxx.xxx/api/admin/web/category/edit/1")

but when i access http://128.199.xxx.xxx/api/admin/web/ its ok, all css loaded

i have setup resource path
$app['asset_path'] = '../web/resources';

![screen shot 2015-05-14 at 12 22 52 pm](https://cloud.githubusercontent.com/assets/2455823/7626485/0a95ee48-fa34-11e4-86da-2f559e094f5b.png)

**Comment by jonseg** [comment]
Hi, try this:

$app['asset_path'] = 'http://128.199.xxx.xxx/api/admin/web/resources';

Thank you.

**Comment by pratamawijaya** [comment]
owh nice, so its must full path with ip 

thanks @jonseg
