### ISSUE TITLE
Does not display tables with somposite primary key

### ISSUE THREAD

**Issue by kusius** [jonseg/crud-admin-generator#83]
Let  table1 have 
- A1 
- A2 (foreign key) 

and the primary key of that table be (A1,A2). 

For some reason those tables are not displayed in the side pane.

**Comment by blag001** [comment]
We don't support composite PK without auto increment for now...
check [`master:`src/console.php#L76](https://github.com/jonseg/crud-admin-generator/blob/master/src/console.php#L76) 

If you think you can add this feature, make a push request ;)
